In [4]:
import magic_default

In [7]:
import pandas as pd

In [8]:
df = pd.read_json('default-cards.jsonl', lines=True)

In [9]:
df.shape

(118595, 89)

In [10]:
pd.set_option('display.max_columns', 88)

In [11]:
df

,object,id,oracle_id,multiverse_ids,mtgo_id,arena_id,tcgplayer_id,cardmarket_id,name,lang,released_at,uri,scryfall_uri,layout,highres_image,image_status,image_updated_at,image_uris,mana_cost,cmc,type_line,oracle_text,colors,color_identity,keywords,produced_mana,all_parts,legalities,games,reserved,game_changer,foil,nonfoil,finishes,oversized,promo,reprint,variation,set_id,set,set_name,set_type,set_uri,set_search_uri,...,rulings_uri,prints_search_uri,collector_number,digital,rarity,card_back_id,artist,artist_ids,illustration_id,border_color,frame,full_art,textless,booster,story_spotlight,prices,related_uris,purchase_uris,mtgo_foil_id,power,toughness,flavor_text,edhrec_rank,penny_rank,promo_types,security_stamp,card_faces,preview,watermark,frame_effects,loyalty,resource_id,printed_name,tcgplayer_etched_id,flavor_name,attraction_lights,color_indicator,printed_text,printed_type_line,variation_of,life_modifier,hand_modifier,content_warning,defense
0,card,0000419b-0bba-4488-8f7a-6194544ce91e,b34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6,[668564],129825.0,91829.0,558404.0,777725.0,Forest,en,2024-08-02,https://api.scryfall.com/cards/0000419b-0bba-4...,https://scryfall.com/card/blb/280/forest?utm_s...,normal,True,highres_scan,2026-07-13 02:46:16+00:00,{'small': 'https://cards.scryfall.io/small/fro...,,0.0,Basic Land — Forest,({T}: Add {G}.),[],[G],[],[G],"[{'object': 'related_card', 'id': 'bddc66f7-4e...","{'standard': 'legal', 'future': 'legal', 'hist...","[paper, mtgo, arena]",False,False,True,True,"[nonfoil, foil]",False,False,True,False,a2f58272-bba6-439d-871e-7a46686ac018,blb,Bloomburrow,expansion,https://api.scryfall.com/sets/a2f58272-bba6-43...,https://api.scryfall.com/cards/search?order=se...,...,https://api.scryfall.com/cards/0000419b-0bba-4...,https://api.scryfall.com/cards/search?order=re...,280,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,David Robert Hovey,[22ab27e3-6476-48f1-a9f7-9a9e86339030],fb2b1ca2-7440-48c2-81c8-84da0a45a626,black,2015,True,False,True,False,"{'usd': '0.38', 'usd_foil': '0.54', 'usd_etche...",{'gatherer': 'https://gatherer.wizards.com/Pag...,{'tcgplayer': 'https://partner.tcgplayer.com/c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,card,0000579f-7b35-4ed3-b44c-db2a538066fe,44623693-51d6-49ad-8cd7-140505caf02f,[109722],25527.0,NaN,14240.0,13850.0,Fury Sliver,en,2006-10-06,https://api.scryfall.com/cards/0000579f-7b35-4...,https://scryfall.com/card/tsp/157/fury-sliver?...,normal,True,highres_scan,2026-07-13 11:47:01+00:00,{'small': 'https://cards.scryfall.io/small/fro...,{5}{R},6.0,Creature — Sliver,All Sliver creatures have double strike.,[R],[R],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal...","[paper, mtgo]",False,False,True,True,"[nonfoil, foil]",False,False,False,False,c1d109bc-ffd8-428f-8d7d-3f8d7e648046,tsp,Time Spiral,expansion,https://api.scryfall.com/sets/c1d109bc-ffd8-42...,https://api.scryfall.com/cards/search?order=se...,...,https://api.scryfall.com/cards/0000579f-7b35-4...,https://api.scryfall.com/cards/search?order=re...,157,False,uncommon,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Paolo Parente,[d48dd097-720d-476a-8722-6a02854ae28b],2fcca987-364c-4738-a75b-099d8a26d614,black,2003,False,False,True,False,"{'usd': '0.48', 'usd_foil': '1.58', 'usd_etche...",{'gatherer': 'https://gatherer.wizards.com/Pag...,{'tcgplayer': 'https://partner.tcgplayer.com/c...,25528.0,3,3,"""A rift opened, and our arrows were abruptly s...",10342.0,12321.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,card,00006596-1166-4a79-8443-ca9f82e6db4e,8ae3562f-28b7-4462-96ed-be0cf7052ccc,[189637],34586.0,NaN,33347.0,21851.0,Kor Outfitter,en,2009-10-02,https://api.scryfall.com/cards/00006596-1166-4...,https://scryfall.com/card/zen/21/kor-outfitter...,normal,True,highres_scan,2026-07-13 11:29:31+00:00,{'small': 'https://cards.scryfall.io/small/fro...,{W}{W},2.0,Creature — Kor Soldier,"When this creature enters, you may attach targ...",[W],[W],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal...","[paper, mtgo]",False,False,True,True,"[nonfoil, foil]",False,False,False,False,eb16a2bd-a218-4e4e-8339-4aa1afc0c8d2,zen,Zendikar,expansion,https://api.scryfall.com/sets/eb16a2bd-a218-4e...,https://api.scryfall.com/cards/search?order=se...,...,https://api.scryfall.com/cards/00006596-1166-4...,https://api.scryfall.com/cards/search?order=re...,21,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Kieran Yanner,[aa7e89ed-d294-4633-9057-ce04dacfcfa4],de0310d1-e97f-46e0-bc16-c980c2adedee,black,2003,False,False,True,False,"{'usd': '0.17', 'usd_foil': '1.84', 'usd_etche...",{'gatherer': 'https://gatherer.wizards.com/Pag...,{'tcgplayer': 'https://partner.tcgplayer.com/c...,34587.0,2,2,"""We take only what we need to survive. Believe...",20963.0,6216.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,card,0000a54c-a511-4925-92dc-01b937f9afad,dc4e2134-f0c2-49aa-9ea3-ebf83af1445c,[],NaN,NaN,98659.0,282862.0,Spirit,en,2015-05-22,https://api.scryfall.com/cards/0000a54c-a511-4...,https://scryfall.com/card/tmm2/5/spirit?utm_so...,token,True,highres_scan,2026-07-13 10:26:14+00:00,{'small': 'https://cards.scryfall.io/small/fro...,,0.0,Token Creature — Spirit,Flying,[W],[W],[Flying],NaN,"[{'object': 'related_card', 'id': '9e371a29-bb...","{'standard': 'not_legal', 'future': 'not_legal...",[paper],False,False,False,True,[nonfoil],False,False,True,False,f7aa47c6-c1e2-4de5-9a68-4406d84bd6bb,tmm2,Modern Masters 2015 Tokens,token,https://api.scryfall.com/sets/f7aa47c6-c1e2-4d...,https://api.scryfall.com/cards/search?order=se...,...,https://api.scryfall.com/cards/0000a54c-a511-4...,https://api.scryfall.com/cards/search?order=re...,5,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Mike Sass,[155bc2cb-038d-4b1f-9990-6178db1d1a21],1dbe0618-dd47-442c-acf6-ac5e4b136e5a,black,2015,False,False,True,False,"{'usd': '0.26', 'usd_foil': None, 'usd_etched'...",{'tcgplayer_infinite_articles': 'https://partn...,{'tcgplayer': 'https://partner.tcgplayer.com/c...,NaN,1,1,NaN,NaN,NaN,[setpromo],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,card,0000cd57-91fe-411f-b798-646e965eec37,9f0d82ae-38bf-45d8-8cda-982b6ead1d72,[435231],65170.0,66119.0,145764.0,301766.0,Siren Lookout,en,2017-09-29,https://api.scryfall.com/cards/0000cd57-91fe-4...,https://scryfall.com/card/xln/78/siren-lookout...,normal,True,highres_scan,2026-07-13 09:42:53+00:00,{'small': 'https://cards.scryfall.io/small/fro...,{2}{U},3.0,Creature — Siren Pirate,"Flying\nWhen this creature enters, it explores...",[U],[U],"[Flying, Explore]",NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal...","[arena, paper, mtgo]",False,False,True,True,"[nonfoil, foil]",False,False,False,False,fe0dad85-54bc-4151-9200-d68da84dd0f2,xln,Ixalan,expansion,https://api.scryfall.com/sets/fe0dad85-54bc-41...,https://api.scryfall.com/cards/search?order=se...,...,https://api.scryfall.com/cards/0000cd57-91fe-4...,https://api.scryfall.com/cards/search?order=re...,78,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Chris Rallis,[a8e7b854-b15a-421a-b66d-6e68187ae285],e0a40a54-9216-4c86-b9e3-daed04abc310,black,2015,False,False,True,False,"{'usd': '0.23', 'usd_foil': '0.41', 'usd_etche...",{'gatherer': 'https://gatherer.wizards.com/Pag...,{'tcgplayer': 'https://partner.tcgplayer.com/c...,65171.0,1,2,NaN,21009.0,14349.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118590,card,fffcbc4e-c6dc-4808-b262-f7c453e74dd8,2979597d-c3cc-4585-a9b7-7fa15641b030,[],NaN,NaN,37957.0,21808.0,Celestine Reef,en,2009-09-30,https://api.scryfall.com/cards/fffcbc4e-c6dc-4...,https://scryfall.com/card/dci/42/celestine-ree...,planar,True,highres_scan,2026-07-13 11:29:48+00:00,{'small': 'https://cards.scryfall.io/small/fro...,,0.0,Plane — Luvion,Creatures without flying or islandwalk can't a...,[],[],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal...",[paper],False,False,False,True,[nonfoil],True,True,True,False,935e91e9-61c2-4b35-a85a-c08fef3b420b,dci,DCI Promos,promo,https://api.scryfall.com/sets/935e91e9-61c2-4b...,https://api.scryfall.com/cards/search?order=se...,...,https://api.scryfall.com/cards/fffcbc4e-c6dc-4...,https://api.scryfall.com/cards/search?order=re...,42,False,rare,7840c131-f96b-4700-9347-2215c43156e6,Donato Giancola,[90332db2-aecb-4d79-917b-95cbeb8d0cb6],dc9573c0-a33c-466b-9208-54b8d66b32fb,black,2003,False,False,False,False,"{'usd': '2.15', 'usd_foil': None, 'usd_etched'...",{'tcgplayer_infinite_articles': 'https://partn...,{'tcgplayer': 'https://partner.tcgplayer.com/c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118591,card,fffce2f7-b619-4483-a75e-916343194641,6ecc61ff-719a-405d-b02a-01607729d05c,[45404],19591.0,NaN,11217.0,893.0,Horned Troll,en,2003-07-28,https://api.scryfall.com/cards/fffce2f7-b619-4...,https://scryfall.com/card/8ed/257/horned-troll...,normal,True,highres_scan,2026-07-13 12:11:12+00:00,{'small': 'https://cards.scryfall.io/small/fro...,{2}{G},3.0,Creature — Troll,{G}: Regenerate this creature.,[G],[G],[Regenerate],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal...","[paper, mtgo]",False,False,False,True,[nonfoil],False,False,True,False,cae8d29d-5979-4d8f-884d-7f3183bcc886,8ed,Eighth Edition,core,https://api.scryfall.com/sets/cae8d29d-5979-4d...,https://api.scryfall.com/cards/search?order=se...,...,https://api.scryfall.com/cards/fffce2f7-b619-4...,https://api.scryfall.com/cards/search?order=re...,257,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Christopher Moeller,[21e10012-06ae-44f2-b38d-3824dd2e73d4],76e4bc9a-2a0c-40f0-9b34-d640c7508c20,white,2003,False,False,True,False,"{'usd': '0.04', 'usd_foil': None, 'usd_etched'...",{'gatherer': 'https://gatherer.wizards.com/Pag...,{'tcgplayer': 'https://partner.tcgplayer.com/c...,19592.0,2,2,Sword hilts jut from some trolls' bodies where...,30518.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118592,card,fffdf7f3-a230-417a-883a-069aabcbcca7,164b064e-de50-468a-b874-b054897a5be9,[633182],117284.0,NaN,513865.0,730169.0,Faerie Bladecrafter,en,2023-09-08,https://api.scryfall.com/cards/fffdf7f3-a230-4...,https://scryfall.com/card/woc/14/faerie-bladec...,normal,True,highres_scan,2026-07-13 03:56:27+00:00,{'small': 'https://cards.scryfall.io/small/fro...,{2}{B},3.0,Creature — Faerie Rogue,Flying\nWhenever one or more Faeries you contr...,[B],[B],[Flying],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal...","[paper, mtgo]",False,False,False,True,[nonfoil],False,False,False,False,51c0814a-2db2-4182-9aac-77340e9a540d,woc,Wilds of Eldraine Commander,commander,https://api.scryfall.com/sets/51c0814a-2db2-41...,https://api.scryfall.com/cards/search?order=se...,...,https://api.scryfall.com/cards/fffdf7f3-a230-4...,https://api.scryfall.com/cards/search?order=re...,14,False,rare,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Jodie Muir,[b09e6cd1-0257-425a-9bbb-5cac3f803443],4732b1bb-c7ae-4816-afa4-4d0d393d6b9f,black,2015,False,False,False,False,"{'usd': '4.31', 'usd_foil': None, 'usd_etched'...",{'gatherer': 'https://gatherer.wizards.com/Pag...,{'tcgplayer': 'https://partner.tcgplayer.com/c...,NaN,2,2,NaN,6109.0,NaN,NaN,oval,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118593,card,fffe7b2b-22c3-4e6a-9b1b-c6d7b29b9f86,d7ebd4a7-c542-469f-8a1c-d48b92fa540a,[439664],66467.0,66631.0,155714.0,315361.0,Exultant Skymarcher,en,2018-01-19,https://api.scryfall.com/cards/fffe7b2b-22c3-4...,https://scryfall.com/card/rix/7/exultant-skyma...,normal,True,highres_scan,2026-07-13 09:35:39+00:00,{'small': 'https://cards.scryfall.io/small/fro...,{1}{W}{W},3.0,Creature — Vampire Soldier,Flying,[W],[W],[Flying],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal...","[arena, paper, mtgo]",False,False,True,True,"[nonfoil, foil]",False,False,False,False,2f7e40fc-772d-4a85-bfdd-01653c41d0fa,rix,Rivals of Ixalan,expansion,https://api.scryfall.com/sets/2f7e40fc-772d-4a...,https://api.scryfall.com/cards/search?order=se...,...,https://api.scryfall.com/cards/fffe7b2b-22c3-4...,https://api.scryfall.com/cards/search?order=re...,7,False,common,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Ryan Yee,[8955dca7-3e37-42b4-83a9-167c78a2178f],023a8518-bc70-4fee-8f3f-2ea4e1eba66b,black,2015,False,False,True,False,"{'usd': '0.04', 'usd_foil': '0.19', 'usd_etche...",{'gatherer': 'https://gatherer.wizards.com/Pag...,{'tcgplayer': 'https://partner.tcgplayer.com/c...,NaN,2,3,"""We have come at last to this holiest of holy ...",26412.0,16886.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118594,card,ffff0825-9996-4ae5-90c8-cb976ccf4ae0,92d6af2f-728e-4e41-87cb-5c90878a2f2f,[],NaN,NaN,449020.0,683861.0,Disintegrate,en,2022-11-28,https://api.scryfall.com/cards/ffff0825-9996-4...,https://scryfall.com/card/30a/137/disintegrate...,normal,False,lowres,2026-07-13 05:11:50+00:00,{'small': 'https://cards.scryfall.io/small/fro...,{X}{R},1.0,Sorcery,Disintegrate deals X damage to any target. If ...,[R],[R],[],NaN,NaN,"{'standard': 'not_legal', 'future': 'not_legal...",[paper],False,False,False,True,[nonfoil],False,False,True,False,c3cddb17-44d9-4abd-8d19-666f6c5171fe,30a,30th Anniversary Edition,memorabilia,https://api.scryfall.com/sets/c3cddb17-44d9-4a...,https://api.scryfall.com/cards/search?order=se...,...,https://api.scryfall.com/cards/ffff0825-9996-4...,https://api.scryfall.com/cards/search?order=re...,137,False,common,049a6229-ace9-4363-816a-60cb8773e95d,Anson Maddocks,[634430a7-b5c3-4e4a-b2ac-164e084e47c9],04b36f31-f3a8-4341-950b-97aebad43e3a,black,2015,False,False,False,False,"{'usd': '1.34', 'usd_foil': None, 'usd_etched'...",{'tcgplayer_infinite_articles': 'https://partn...,{'tcgplayer': 'https://partner.tcgplayer.com/c...,NaN,NaN,NaN,NaN,16029.0,14704.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
list(df)

['object',
 'id',
 'oracle_id',
 'multiverse_ids',
 'mtgo_id',
 'tcgplayer_id',
 'cardmarket_id',
 'name',
 'lang',
 'released_at',
 'uri',
 'scryfall_uri',
 'layout',
 'highres_image',
 'image_status',
 'image_updated_at',
 'image_uris',
 'mana_cost',
 'cmc',
 'type_line',
 'oracle_text',
 'power',
 'toughness',
 'colors',
 'color_identity',
 'keywords',
 'all_parts',
 'legalities',
 'games',
 'reserved',
 'game_changer',
 'foil',
 'nonfoil',
 'finishes',
 'oversized',
 'promo',
 'reprint',
 'variation',
 'set_id',
 'set',
 'set_name',
 'set_type',
 'set_uri',
 'set_search_uri',
 'scryfall_set_uri',
 'rulings_uri',
 'prints_search_uri',
 'collector_number',
 'digital',
 'rarity',
 'watermark',
 'flavor_text',
 'card_back_id',
 'artist',
 'artist_ids',
 'illustration_id',
 'border_color',
 'frame',
 'frame_effects',
 'security_stamp',
 'full_art',
 'textless',
 'booster',
 'story_spotlight',
 'edhrec_rank',
 'preview',
 'prices',
 'related_uris',
 'purchase_uris',
 'mtgo_foil_id',
 'penny_rank',
 'arena_id',
 'promo_types',
 'card_faces',
 'produced_mana',
 'resource_id',
 'tcgplayer_etched_id',
 'loyalty',
 'life_modifier',
 'hand_modifier',
 'attraction_lights',
 'color_indicator',
 'flavor_name',
 'content_warning',
 'variation_of',
 'printed_type_line',
 'printed_text',
 'defense']

In [48]:
filt = df[['name', 'set', 'mana_cost', 'colors', 'color_identity']]

In [49]:
filt

,name,set,mana_cost,colors,color_identity
0,"Nissa, Worldsoul Speaker",drc,{3}{G},[G],[G]
1,Mine Security,yeoe,{1}{R},[R],[R]
2,Static Orb,7ed,{3},[],[]
3,Sensory Deprivation,m14,{U},[U],[U]
4,Kavaron Consumed,yeoe,{3}{R}{R},[R],[R]
...,...,...,...,...,...
38700,Without Weakness,hou,{1}{B},[B],[B]
38701,Firesong and Sunspeaker,2x2,{4}{R}{W},"[R, W]","[R, W]"
38702,"Toralf, God of Fury // Toralf's Hammer",khm,NaN,NaN,[R]
38703,"Samut, the Tested",hou,{2}{R}{G},"[G, R]","[G, R]"
38704,Sinew Sliver,cmm,{1}{W},[W],[W]